"""Choose layouts using the full evidence-based director; ask the local model only for process labels."""
import re
from typing import Annotated

from pydantic import Field, StringConstraints, model_validator

from backend.llm.gguf_llm import create_local_llm
from backend.llm.prompts import build_retry_prompt
from backend.schemas.video_schema import StrictContent, VideoScript, Scene, words
from backend.services.json_parser import parse_json_object
from backend.services.director import direct_scene


class ProcessLabels(StrictContent):
    items: Annotated[list[Annotated[str, StringConstraints(min_length=1, max_length=70)]], Field(min_length=3, max_length=3)]

    @model_validator(mode="after")
    def readable(self):
        if len(set(s.casefold() for s in self.items)) != 3:
            raise ValueError("Use three distinct steps")
        for text in self.items:
            Scene.plain_text(text)
            if len(words(text)) > 10:
                raise ValueError("Each step must contain at most ten words")
        return self


def build_visuals(video: VideoScript, *, engine=None, offline=False, threads=2) -> dict:
    """Build visual plans for every scene using the full evidence-based director.

    For ``process`` scenes whose items were generated by regex (First/Next/Finally
    triggers), the LLM is optionally asked to produce shorter diagram labels.
    All other scene types (neural_net, code, stat_card, comparison, relationship,
    cycle, timeline, components, chart, water_cycle, explanation, example, takeaway,
    title) are handled deterministically by director.direct_scene() without any LLM
    call, so the engine is only started when actually needed.
    """
    total = len(video.scenes)
    scenes, warnings = [], []

    # Determine whether we need the LLM at all (only for process label enrichment).
    process_indices = [
        i for i, s in enumerate(video.scenes)
        if direct_scene(s, i, total).get("kind") == "process"
    ]
    needs_llm = bool(process_indices)

    owns_engine = engine is None
    engine_instance = None

    def get_engine():
        nonlocal engine_instance
        if engine_instance is None:
            engine_instance = engine or create_local_llm(
                offline=offline, threads=threads,
                on_progress=lambda s: print(s, flush=True),
            )
        return engine_instance

    try:
        for index, scene in enumerate(video.scenes):
            # Full evidence-based detection: neural_net, code, stat_card, process,
            # comparison, relationship, cycle, timeline, components, chart, water_cycle,
            # explanation, example, takeaway, title.
            visual = direct_scene(scene, index, total)

            # Headline-based fallback: if the scene reads as 'explanation' but the headline
            # signals a mechanism or process, promote to 'process' so the LLM can produce
            # concise diagram labels (preserves the original build_visuals behaviour).
            if visual["kind"] == "explanation" and re.search(
                r"\b(mechanism|how\b.{0,30}\bwork|process|steps)\b",
                scene.headline, re.IGNORECASE,
            ):
                visual["kind"] = "process"

            if not getattr(scene, 'beats', None):
                visual.pop('directed', None)

            # For process scenes, try to improve the diagram labels with the LLM.
            if visual["kind"] == "process" and not visual.get("items"):
                original = (
                    f"Summarize this explanation as three ordered process steps for a diagram.\n"
                    f"Topic: {video.topic}\n"
                    f"Explanation: {scene.body} {scene.narration}\n"
                    f"Return JSON only with one key \"items\": an array of exactly three short labels, "
                    f"each at most eight words. Use only information supported by the explanation. "
                    f"No claims about guaranteed accuracy."
                )
                prompt = original
                for attempt in range(1, 4):
                    print(f"  Visual scene {scene.id}: process labels, attempt {attempt}/3", flush=True)
                    raw = get_engine().generate(prompt, max_new_tokens=180, temperature=0)
                    try:
                        draft = ProcessLabels.model_validate(parse_json_object(raw))
                        visual["items"] = draft.items
                        break
                    except ValueError as exc:
                        if attempt == 3:
                            visual["kind"] = "explanation"
                            warnings.append({
                                "scene": scene.id,
                                "message": "Process labels failed validation; using the original explanation layout.",
                            })
                        prompt = build_retry_prompt(original, raw, str(exc), attempt + 1)

            scenes.append({"id": scene.id, **visual})

        return {
            "scenes": scenes,
            "warnings": warnings,
            "notice": (
                "Evidence-based diagrams with narration cues. "
                "Process labels may be model-generated summaries; review before publishing."
            ),
        }

    finally:
        if owns_engine and engine_instance is not None and hasattr(engine_instance, "close"):
            engine_instance.close()
